# Indicates whether to host application purely locally - this allows for use of subdomains
localhost: false

# Local IP address to host web app
local-ip:
  mac: 10.0.0.30
  win: 10.20.12.173

# Port number to host web app - use 5000 as default
port: 5000

# Indicate whether to run web app in debug mode
debug: true

# GitHub repositories to display in /projects page
github-repos: ['pycraigslist', 'youtube2audio', 'actransit-map', 'visuaudio', 'jupyterblack', 'astree', 'soil-moisture-display', 'personal-website-2']
