# Local IP address to host web app - use 127.0.0.1 as default
local-ip: 127.0.0.1

# Port number to host web app - use 5000 as default
port: 5000

# Indicate whether to run web app in debug mode
debug: true

# GitHub properties to display in /projects page
github:
  repos: ['pycraigslist', 'youtube2audio', 'visuaudio', 'actransit-map', 'jupyterblack', 'astree', 'img-optimize', 'soil-moisture-display', 'personal-website-1', 'personal-website-2']
